name: Shuttle Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          name: "rainbow-bid-backend"
          allow-dirty: "true"
          no-test: "false"
          cargo-shuttle-version: "0.28.1"
          secrets: |
            ALLOWED_ORIGIN = '${{ secrets.ALLOWED_ORIGIN }}'
            JWT_KEY = '${{ secrets.JWT_KEY }}'
            JWT_DURATION = '${{ secrets.JWT_DURATION }}'
            FINALIZE_AUCTIONS_CRON = '${{ secrets.FINALIZE_AUCTIONS_CRON }}'