name: Shuttle Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          name: "rainbow-bid-backend"
          allow-dirty: "true"
          no-test: "false"
          cargo-shuttle-version: "0.28.1"
#          secrets: |
#            MY_AWESOME_SECRET_1 = '${{ secrets.SECRET_1 }}'
#            MY_AWESOME_SECRET_2 = '${{ secrets.SECRET_2 }}'